### ISSUE TITLE
UI related: resorting of all transactions

### ISSUE THREAD

**Issue by Cryptoford** [Polkadex-Substrate/Ido-Thea-beta-testers-feedback#8]
showing the most recent transaction by date first should appear more intuitive on the UI
![pdex tmanager sug](https://user-images.githubusercontent.com/90802124/162580560-b0fb875f-7981-4686-98b6-19bd65a0241d.jpg)

**Comment by jmansfie** [comment]
Does this page refresh automatically? If not it may need some type of refresh button added

**Comment by charleslukes** [comment]
> Does this page refresh automatically? If not it may need some type of refresh button added

Yes it does, whenever you come to this page we fetch all users transaction both successful and pending. 
This has been fixed with https://github.com/Polkadex-Substrate/Polkadex-PolkaIDO-Frontend/pull/271
